### ISSUE TITLE
how many iterations you take to make it converge

### ISSUE THREAD

**Issue by zyxnine9** [MasfiqurRahaman/Find-food-and-survive-from-enemy#1]
I use PyTorch to reimplement this project, however, it doesn't converge at all with the same environment and the same parameters. could you tell me how many iterations you take to make it converge?

**Comment by masfiqur-rahaman** [comment]
Hi. Thank you for showing interest. It took 40,000 episodes.

**Comment by zyxnine9** [comment]
thanks. I train it 25k times. it seems like I need to train it more
